FROM eclipse-temurin:21-jdk

WORKDIR /app

COPY gradle gradle
COPY gradlew .
COPY build.gradle .
COPY settings.gradle .
COPY src src

RUN chmod +x ./gradlew

CMD ["./gradlew", "test", "--info", "--stacktrace"]